# Ex 1 Basic Propositions SymPy

In [1]:
from sympy import symbols,sqrt,pretty

In [2]:
p,q=symbols("p q")

In [3]:
F=p&(q|~p)

In [4]:
print(pretty(p),"\t\t",pretty(q),"\t\t",pretty(F))
for vp in [False,True]:
    for vq in [False,True]:
        print("p=",vp,"\t","q=",vq,"\t",F.subs({p:vp,q:vq}))

p 		 q 		 p ∧ (q ∨ ¬p)
p= False 	 q= False 	 False
p= False 	 q= True 	 False
p= True 	 q= False 	 False
p= True 	 q= True 	 True

# Ex 2 NOT, AND, OR connectives

In [5]:
from sympy import Not,And,Or

In [6]:
F1=Not(p)
F2=And(p,q)
F3=p|q

In [7]:
print(pretty(p),"\t",pretty(q),"\t",pretty(F1),"\t",pretty(F2),"\t",pretty(F3))
for vp in [False,True]:
    for vq in [False,True]:
        print(vp,"\t",vq,"\t",F1.subs({p:vp,q:vq}),"\t",F2.subs({p:vp,q:vq}),"\t",F3.subs({p:vp,q:vq}))

p 	 q 	 ¬p 	 p ∧ q 	 p ∨ q
False 	 False 	 True 	 False 	 False
False 	 True 	 True 	 False 	 True
True 	 False 	 False 	 False 	 True
True 	 True 	 False 	 True 	 True

# Ex 3 Implication Truth Table

In [8]:
from sympy import Implies
from sympy.logic.boolalg import truth_table

In [9]:
I=Implies(p,q)

In [10]:
print(pretty(p),"\t",pretty(q),"\t",pretty(I))
for row in truth_table(I,[p,q]):
    vL,vr=row
    vp,vq=vL
    print(vp,"\t",vq,"\t",vr)

p 	 q 	 p → q
0 	 0 	 True
0 	 1 	 True
1 	 0 	 False
1 	 1 	 True

The only row where $p \Rightarrow q$ is *False* is where p is *True* and q is *False*, whitch means we canoot start with a *True* Statement and end up with a *False* statement, *True* Always Implies *True*.

# Ex 3 bis

In [11]:
import pandas as pd
def Truth_Table(Exprs,Vars):
    A=[]
    for row in truth_table(Vars[0],Vars):
        vL,vr=row
        A.append(vL)
    for exp in Exprs:
        for i,row in enumerate(truth_table(exp,Vars)):
            _,vr=row
            A[i].append(vr)
    return pd.DataFrame(A,columns=Vars+[pretty(exp) for exp in Exprs])
Truth_Table([p|q,p&q,p>>q],[p,q])

   p  q  p ∨ q  p ∧ q  p → q
0  0  0  False  False   True
1  0  1   True  False   True
2  1  0   True  False  False
3  1  1   True   True   True

# Ex 4 Biconditional (↔) Equivalent

In [12]:
from sympy import Equivalent

In [13]:
Eq=Equivalent(p,q)
print(pretty(p),"\t",pretty(q),"\t",pretty(Eq))
for row in truth_table(Eq,[p,q]):
    vL,vr=row
    vp,vq=vL
    print(vp,"\t",vq,"\t",vr)

p 	 q 	 p ⇔ q
0 	 0 	 True
0 	 1 	 False
1 	 0 	 False
1 	 1 	 True

# Ex 5 Operator Precedence

In [14]:
r=symbols("r")

In [15]:
A=(~p&q)|r
B=~p&(q|r)
print(pretty(A),"\t\t",pretty(B))
D={p:True,q:False,r:True}
print(A.subs(D),"\t\t\t",B.subs(D))

r ∨ (q ∧ ¬p) 		 ¬p ∧ (q ∨ r)
True 			 False

# Ex 6 Converse, Contrapositive, Inverse implication

In [16]:
Names=["Original","Converse","Contrapositive","Inverse"]
Formules=[p>>q,q>>p,~q>>~p,~p>>~q]

In [17]:
from sympy import simplify_logic
import pandas as pd

In [18]:
a = {
    "Formule": [pretty(F) for F in  Formules],
    "Simplification":[pretty(simplify_logic(F)) for F in  Formules]
}
df = pd.DataFrame(a, index=Names)

df

                Formule Simplification
Original          p → q         q ∨ ¬p
Converse          q → p         p ∨ ¬q
Contrapositive  ¬q → ¬p         q ∨ ¬p
Inverse         ¬p → ¬q         p ∨ ¬q

# Ex 7 Tautology Detection satisfiable

In [19]:
from sympy import satisfiable

In [20]:
def is_tautology(expr) -> bool:
    return not satisfiable(Not(expr))

In [21]:
Formules7=[p|~p,(p>>q)>>(~q>>~p),p&~p,(p|q)>>p,(p&q)>>p]
D7={"Is Tautology":["✅" if  is_tautology(expr) else  "❌"  for expr in Formules7]}
pd.DataFrame(D7,index=[pretty(F) for F in Formules7])

                    Is Tautology
p ∨ ¬p                         ✅
(p → q) → (¬q → ¬p)            ✅
p ∧ ¬p                         ❌
(p ∨ q) → p                    ❌
(p ∧ q) → p                    ✅

# Ex 8 Contradiction Detection satisfiable

In [22]:
def is_contradiction(expr) -> bool:
    return not satisfiable(expr)

In [23]:
Formules7=[p&~p,p|~p,(p>>q)&p&~q]
D7={"Is Contradiction":["✅" if  is_contradiction(expr) else  "❌"  for expr in Formules7]}
pd.DataFrame(D7,index=[pretty(F) for F in Formules7])

                 Is Contradiction
p ∧ ¬p                          ✅
p ∨ ¬p                          ❌
p ∧ (p → q) ∧ ¬q                ✅

# Ex 9  Exclusive OR Xor

In [24]:
from sympy import Xor
xor_direct=Xor(p,q)
xor_expanded=(p|q)&~(p&q)
is_tautology(Equivalent(xor_direct, xor_expanded))

True

In [25]:
Truth_Table([xor_direct],[p,q])

   p  q  p ⊻ q
0  0  0  False
1  0  1   True
2  1  0   True
3  1  1  False

for the or Gate $ P\lor Q$ at least one of P and Q must be True

for the xor Gate $P \oplus Q$ at least one of P or q must be True, but not simultaniously.

# Ex 10 Logic Gates — NAND and NOR gates

In [27]:
from sympy.logic import Nand,Nor

In [28]:
Truth_Table([Nand(p,q),Nor(p,q)],[p,q])

   p  q ¬(p ∧ q) ¬(p ∨ q)
0  0  0     True     True
1  0  1     True    False
2  1  0     True    False
3  1  1    False    False

In [127]:
def NAND(a,b):
    return ~(a&b)

In [128]:
def NOR(a,b):
    return ~(a|b)

In [129]:
def NEG_byNand(p):
    return Nand(p,p)

In [130]:
NEG_byNand(p)

~p

In [131]:
def AND_byNand(p,q):
    return simplify_logic(Nand(Nand(p,q),Nand(p,q)))

In [132]:
AND_byNand(p,q)

p & q

In [133]:
def OR_byNand(p,q):
    return NEG_byNand(AND_byNand(Nand(p,p),Nand(q,q)))

In [134]:
OR_byNand(p,q)

~(~p & ~q)

In [135]:
from sympy.logic import Equivalent

In [136]:
is_tautology(Equivalent(~p,NEG_byNand(p)))

True

In [137]:
is_tautology(Equivalent(p|q,OR(p,q)))

True

In [138]:
is_tautology(Equivalent(p|q,OR(p,q)))

True

In [139]:
is_tautology(Equivalent(p&q,AND_byNand(p,q)))

True

In [140]:
def NEG_byNOR(p):
    return NOR(p,p)

In [141]:
NEG_byNOR(p)

~p

In [142]:
def AND_byNOR(p,q):
    return NOR(NOR(p,p),NOR(q,q))

In [145]:
AND_byNOR(p,q)

~(~p | ~q)

In [146]:
def OR_byNOR(p,q):
    return NOR(NOR(p,q),NOR(p,q))

In [147]:
OR_byNOR(p,q)

p | q

In [148]:
is_tautology(Equivalent(p&q,AND_byNOR(p,q)))

True

In [149]:
is_tautology(Equivalent(p|q,OR_byNOR(p,q)))

True

In [151]:
is_tautology(Equivalent(~p,NEG_byNOR(p)))

True

Single-Gate Computers: Apollo Guidance Computer
Why engineers did this
1. Manufacturing Efficiency: Buying thousands of identical parts is cheaper than buying small quantities of many different parts.
2. Reliability: It is easier to rigorously test and perfect the production of one specific circuit design.
3. Simplicity: Standardizing the voltage and timing across the entire machine becomes much easier when every component behaves identically.

# Ex 11 Three-Variable Truth Table truth_table

In [154]:
F=(p>>q& q>>r)>>(p>>r)
F

Implies((Implies(p, q)) & (Implies(q, r)), Implies(p, r))

In [155]:
Truth_Table([F],[p,q,r])

   p  q  r ((p → q) ∧ (q → r)) → (p → r)
0  0  0  0                          True
1  0  0  1                          True
2  0  1  0                          True
3  0  1  1                          True
4  1  0  0                          True
5  1  0  1                          True
6  1  1  0                          True
7  1  1  1                          True

In [156]:
is_tautology(F)

True

in generale $2^n$ for n variables